# Generated by Django 4.2.2 on 2023-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='resource_num',
        ),
        migrations.AlterField(
            model_name='course',
            name='max_selected_num',
            field=models.IntegerField(),
        ),
    ]
