# Generated by Django 4.2.2 on 2023-06-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_course_resource_num_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="max_selected_num",
            new_name="max_select_num",
        ),
    ]
