# Generated by Django 4.2.2 on 2023-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_rename_course_teacher_course_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="course_id",
            new_name="course",
        ),
    ]
