name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 替换为你要使用的Python版本

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2
      with:
        server: ${{ secrets.SERVER_IP }}  # 将服务器IP地址存储在GitHub Secrets中
        username: ${{ secrets.SERVER_USERNAME }}  # 将服务器用户名存储在GitHub Secrets中
        password: ${{ secrets.SERVER_PASSWORD }}  # 将服务器密码存储在GitHub Secrets中
        source: ./Database_Course_Design_Backend  # 替换为你的Django工程目录
        target: /path/to/deploy  # 替换为你的服务器上用于部署的目录路径
